receptor = ../gpu_dock/TDP43.pdbqt
ligand = _xua_nativo.pdbqt
center_x = 13.8
center_y = 35.7
center_z = 57.1
size_x = 18
size_y = 18
size_z = 18
exhaustiveness = 16
num_modes = 9
seed = 42
out = _xua_redock_out.pdbqt
