receptor = ../gpu_dock/TDP43.pdbqt
ligand = _dna_nativo.pdbqt
center_x = 16.3
center_y = 41.1
center_z = 48.5
size_x = 24
size_y = 24
size_z = 24
exhaustiveness = 16
num_modes = 9
seed = 42
out = _dna_redock_out.pdbqt
